# Generated by Django 2.2 on 2019-05-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190514_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruteur',
            name='nom_entreprise',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='nom_entreprise',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='code_postal',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='departement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='ville',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='AdresseEntreprise',
        ),
    ]
